# Generated by Django 4.0 on 2021-12-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastInCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('max_temperature', models.FloatField(null=True)),
                ('min_temperature', models.FloatField(null=True)),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('cloudiness', models.FloatField(null=True)),
                ('description', models.CharField(max_length=250)),
                ('wind_speed', models.FloatField(null=True)),
                ('wind_degrees', models.FloatField(null=True)),
            ],
        ),
    ]
